Check CSP hashes during build

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -3,7 +3,7 @@ on:
   pull_request:
   push:
     branches:
-    - master
+      - master
 
 env:
   ECR_REGISTRY: 307238562370.dkr.ecr.eu-west-1.amazonaws.com
@@ -23,9 +23,9 @@ jobs:
   check-licenses:
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v3
-    - name: Reuse Compliance Check
-      uses: fsfe/reuse-action@v1
+      - uses: actions/checkout@v3
+      - name: Reuse Compliance Check
+        uses: fsfe/reuse-action@v1
 
   proxy:
     runs-on: ubuntu-latest
@@ -263,6 +263,25 @@ jobs:
           ./build.sh
           cd ../frontend
           ./build-docker.sh test
+
+      - name: Check inline CSP hashes
+        run: |
+          calculated_hashes=$(docker run --rm "${{ steps.build-builder.outputs.image }}" yarn calculate-csp-hashes)
+          configured_template_hashes=$(cat ./proxy/files/etc/nginx/conf.d/nginx.conf.template | grep 'set $loadFailedInlineScript' | grep -oE '"[^"]+"' | tr -d '"')
+
+          if [ "$calculated_hashes" != "$configured_template_hashes" ]; then
+            echo "Nginx config template config CSP mismatch: $calculated_hashes != $configured_template_hashes"
+            echo "Change the loadFailedInlineScript variable to the new calculated hash(es)."
+            exit 1
+          fi
+
+          configured_compose_hashes=$(cat ./compose/proxy/nginx.conf | grep 'set $loadFailedInlineScript' | grep -oE '"[^"]+"' | tr -d '"')
+
+          if [ "$calculated_hashes" != "$configured_compose_hashes" ]; then
+            echo "Nginx compose config CSP mismatch: $calculated_hashes != $configured_compose_hashes"
+            echo "Change the loadFailedInlineScript variable to the new calculated hash(es)."
+            exit 1
+          fi
 
       - name: Lint
         if: ${{ !github.event.pull_request.head.repo.fork }}
@@ -596,12 +615,6 @@ jobs:
 
       - name: Run e2e tests for fork
         if: ${{ github.event.pull_request.head.repo.fork }}
-        run: |
-          ./bin/split-test.sh "${{ matrix.test_chunk_number }}" "${{ matrix.test_chunk_count }}"
-          cd ./compose
-          ./build.sh
-          ./test-e2e build
-          BUILD=false ./test-e2e run playwright
 
       - name: Store screenshots
         uses: actions/upload-artifact@v3
@@ -723,8 +736,8 @@ jobs:
         uses: actions/checkout@v3
         with:
           repository: espoon-voltti/evaka-infra
-          ssh-key: '${{ secrets.SSH_KEY }}'
-          ref: 'refs/heads/master'
+          ssh-key: "${{ secrets.SSH_KEY }}"
+          ref: "refs/heads/master"
 
       - name: Write AWS config
         shell: bash
